services:
  mysql:
    container_name: mysql_container
    build: 
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
    env_file:
      - ./mysql/mysql.env
    restart: unless-stopped
    networks:
      - final_project_network

  api:
    depends_on:
      - mysql
    container_name: api_container
    build: 
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    env_file:
      - ./api/api.env
    networks:
      - final_project_network

networks:
  final_project_network:
    external: false
