services:
  mysql:
    image: mysql:latest
    container_name: mysql_container

    env_file: ./mysql/mysql.env  
    ports:
      - "3306:3306"
    volumes:
      #- ./mysql/db/data.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/db:/docker-entrypoint-initdb.d


    restart: unless-stopped
    networks:
      - final_project_network


  api:
    depends_on:
      - mysql
    container_name: api_container
    build: 
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./api:/app
    ports:
      - "8003:8000" #Se puede entrar a los datos sin html desde el 8003
    env_file:
      - ./api/api.env
    networks:
      - final_project_network

  
  frontend:
    depends_on:
      - api
      - mysql
    container_name: frontend_container
    build: 
      context: ./frontend_folder
      dockerfile: Dockerfile
    # volumes:
    #   - ./frontend_folder:/app

    restart: unless-stopped
    #expose:
    #  - "8001"
    ports:
      - "8000:8000" #Se entra desde el 8000 y se conecta al 8000 (API)

    #environment:
    #  - SPRING_PROFILES_ACTIVE=no-db #Perfil no db

    networks:
      - final_project_network


networks:
  final_project_network:
    external: false
