services:
  mysql:
    image: mysql:latest
    container_name: mysql_container

    env_file: ./mysql/mysql.env  
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db/products_table.sql:/docker-entrypoint-initdb.d/init.sql


    restart: unless-stopped
    networks:
      - final_project_network


  api:
    depends_on:
      - mysql
    container_name: api_container
    build: 
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    env_file:
      - ./api/api.env
    networks:
      - final_project_network

  
  frontend:
    depends_on:
      - api
    container_name: frontend_container
    build: 
      context: ./frontend_folder
      dockerfile: Dockerfile

    restart: unless-stopped
    #expose:
    #  - "8000"
    ports:
      - "8001:8000"

    environment:
      - SPRING_PROFILES_ACTIVE=no-db #Perfil no db

    networks:
      - final_project_network


networks:
  final_project_network:
    external: false
